// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://www.amazingsaltedfish.com",
        "contact": {
            "name": "author:guoyueyang",
            "url": "http://www.amazingsaltedfish.com",
            "email": "guoyueyang@126.com"
        },
        "license": {
            "name": "License:MIT",
            "url": "https://spdx.org/licenses/MIT.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/struct/": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "结构体信息",
                    "更新"
                ],
                "summary": "更新一个结构信息",
                "parameters": [
                    {
                        "description": "结构体信息",
                        "name": "structInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateStructReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UpdateStructResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.BaseResp"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "结构体信息",
                    "新建"
                ],
                "summary": "新建一个结构信息",
                "parameters": [
                    {
                        "description": "结构体信息",
                        "name": "structInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateStructReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CreateStructResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.BaseResp"
                        }
                    }
                }
            }
        },
        "/struct/detail/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "结构体信息",
                    "获取"
                ],
                "summary": "获取一个结构信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "struct的ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetStructResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.BaseResp"
                        }
                    }
                }
            }
        },
        "/struct/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "结构体信息",
                    "获取",
                    "列表"
                ],
                "summary": "获取结构信息列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分页信息, 页数从1开始",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页信息, 每页最大500",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetStructListResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.BaseResp"
                        }
                    }
                }
            }
        },
        "/struct/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "结构体信息",
                    "删除"
                ],
                "summary": "删除一个结构信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "struct的ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.DeleteStructResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.BaseResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.BaseResp": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "结果码",
                    "type": "integer"
                },
                "msg": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "model.CreateFieldInfo": {
            "type": "object",
            "properties": {
                "fieldComment": {
                    "description": "字段注释",
                    "type": "string"
                },
                "fieldIsList": {
                    "description": "是否为 列表",
                    "type": "boolean"
                },
                "fieldName": {
                    "description": "字段名",
                    "type": "string"
                },
                "fieldSort": {
                    "description": "排序位置",
                    "type": "integer"
                },
                "fieldStructId": {
                    "description": "对应结构体ID, 当 FType 为 FieldTypeStruct 时 有用",
                    "type": "integer"
                },
                "fieldType": {
                    "description": "字段类型",
                    "type": "integer"
                }
            }
        },
        "model.CreateStructReq": {
            "type": "object",
            "properties": {
                "comment": {
                    "description": "字段注释",
                    "type": "string"
                },
                "fieldList": {
                    "description": "字段信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CreateFieldInfo"
                    }
                }
            }
        },
        "model.CreateStructResp": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "结果码",
                    "type": "integer"
                },
                "id": {
                    "description": "创建成功后的ID",
                    "type": "integer"
                },
                "msg": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "model.DeleteStructResp": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "结果码",
                    "type": "integer"
                },
                "id": {
                    "description": "删除的结构体ID",
                    "type": "integer"
                },
                "msg": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "model.Field": {
            "type": "object",
            "properties": {
                "fieldComment": {
                    "description": "字段注释",
                    "type": "string"
                },
                "fieldId": {
                    "description": "字段ID",
                    "type": "integer"
                },
                "fieldIsList": {
                    "description": "是否为 列表",
                    "type": "boolean"
                },
                "fieldName": {
                    "description": "字段名",
                    "type": "string"
                },
                "fieldSort": {
                    "description": "排序位置",
                    "type": "integer"
                },
                "fieldStructId": {
                    "description": "对应结构体ID, 当 FType 为 FieldTypeStruct 时 有用",
                    "type": "integer"
                },
                "fieldType": {
                    "description": "字段类型",
                    "type": "integer"
                },
                "parentId": {
                    "description": "对应结构体ID",
                    "type": "integer"
                }
            }
        },
        "model.GetStructListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "结果码",
                    "type": "integer"
                },
                "list": {
                    "description": "结构体列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.StructInfo"
                    }
                },
                "msg": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "model.GetStructResp": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "结果码",
                    "type": "integer"
                },
                "info": {
                    "description": "结构体信息",
                    "type": "object",
                    "$ref": "#/definitions/model.StructInfo"
                },
                "msg": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "model.StructInfo": {
            "type": "object",
            "properties": {
                "comment": {
                    "description": "备注信息",
                    "type": "string"
                },
                "fieldList": {
                    "description": "字段",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Field"
                    }
                },
                "id": {
                    "description": "结构体ID",
                    "type": "integer"
                }
            }
        },
        "model.UpdateStructReq": {
            "type": "object",
            "properties": {
                "comment": {
                    "description": "备注信息",
                    "type": "string"
                },
                "fieldList": {
                    "description": "字段",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Field"
                    }
                },
                "id": {
                    "description": "结构体ID",
                    "type": "integer"
                }
            }
        },
        "model.UpdateStructResp": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "结果码",
                    "type": "integer"
                },
                "id": {
                    "description": "更新的结构体ID",
                    "type": "integer"
                },
                "msg": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Amazing Salted Fish API",
	Description: "this is [amazing salted fish] swagger api page.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
