definitions:
  model.BaseResp:
    properties:
      code:
        description: 结果码
        type: integer
      msg:
        description: 提示信息
        type: string
    type: object
  model.CreateFieldInfo:
    properties:
      fieldComment:
        description: 字段注释
        type: string
      fieldIsList:
        description: 是否为 列表
        type: boolean
      fieldName:
        description: 字段名
        type: string
      fieldSort:
        description: 排序位置
        type: integer
      fieldStructId:
        description: 对应结构体ID, 当 FType 为 FieldTypeStruct 时 有用
        type: integer
      fieldType:
        description: 字段类型
        type: integer
    type: object
  model.CreateStructReq:
    properties:
      comment:
        description: 字段注释
        type: string
      fieldList:
        description: 字段信息
        items:
          $ref: '#/definitions/model.CreateFieldInfo'
        type: array
    type: object
  model.CreateStructResp:
    properties:
      code:
        description: 结果码
        type: integer
      id:
        description: 创建成功后的ID
        type: integer
      msg:
        description: 提示信息
        type: string
    type: object
  model.DeleteStructResp:
    properties:
      code:
        description: 结果码
        type: integer
      id:
        description: 删除的结构体ID
        type: integer
      msg:
        description: 提示信息
        type: string
    type: object
  model.Field:
    properties:
      fieldComment:
        description: 字段注释
        type: string
      fieldId:
        description: 字段ID
        type: integer
      fieldIsList:
        description: 是否为 列表
        type: boolean
      fieldName:
        description: 字段名
        type: string
      fieldSort:
        description: 排序位置
        type: integer
      fieldStructId:
        description: 对应结构体ID, 当 FType 为 FieldTypeStruct 时 有用
        type: integer
      fieldType:
        description: 字段类型
        type: integer
      parentId:
        description: 对应结构体ID
        type: integer
    type: object
  model.GetStructListResp:
    properties:
      code:
        description: 结果码
        type: integer
      list:
        description: 结构体列表
        items:
          $ref: '#/definitions/model.StructInfo'
        type: array
      msg:
        description: 提示信息
        type: string
    type: object
  model.GetStructResp:
    properties:
      code:
        description: 结果码
        type: integer
      info:
        $ref: '#/definitions/model.StructInfo'
        description: 结构体信息
        type: object
      msg:
        description: 提示信息
        type: string
    type: object
  model.StructInfo:
    properties:
      comment:
        description: 备注信息
        type: string
      fieldList:
        description: 字段
        items:
          $ref: '#/definitions/model.Field'
        type: array
      id:
        description: 结构体ID
        type: integer
    type: object
  model.UpdateStructReq:
    properties:
      comment:
        description: 备注信息
        type: string
      fieldList:
        description: 字段
        items:
          $ref: '#/definitions/model.Field'
        type: array
      id:
        description: 结构体ID
        type: integer
    type: object
  model.UpdateStructResp:
    properties:
      code:
        description: 结果码
        type: integer
      id:
        description: 更新的结构体ID
        type: integer
      msg:
        description: 提示信息
        type: string
    type: object
info:
  contact:
    email: guoyueyang@126.com
    name: author:guoyueyang
    url: http://www.amazingsaltedfish.com
  description: this is [amazing salted fish] swagger api page.
  license:
    name: License:MIT
    url: https://spdx.org/licenses/MIT.html
  termsOfService: http://www.amazingsaltedfish.com
  title: Amazing Salted Fish API
  version: 0.0.1
paths:
  /struct/:
    post:
      consumes:
      - application/json
      parameters:
      - description: 结构体信息
        in: body
        name: structInfo
        required: true
        schema:
          $ref: '#/definitions/model.CreateStructReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.CreateStructResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.BaseResp'
      summary: 新建一个结构信息
      tags:
      - 结构体信息
      - 新建
    put:
      consumes:
      - application/json
      parameters:
      - description: 结构体信息
        in: body
        name: structInfo
        required: true
        schema:
          $ref: '#/definitions/model.UpdateStructReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UpdateStructResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.BaseResp'
      summary: 更新一个结构信息
      tags:
      - 结构体信息
      - 更新
  /struct/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: struct的ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.DeleteStructResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.BaseResp'
      summary: 删除一个结构信息
      tags:
      - 结构体信息
      - 删除
  /struct/detail/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: struct的ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetStructResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.BaseResp'
      summary: 获取一个结构信息
      tags:
      - 结构体信息
      - 获取
  /struct/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: 分页信息, 页数从1开始
        in: query
        name: pageNum
        required: true
        type: integer
      - description: 分页信息, 每页最大500
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetStructListResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.BaseResp'
      summary: 获取结构信息列表
      tags:
      - 结构体信息
      - 获取
      - 列表
swagger: "2.0"
